### ISSUE TITLE
Measurments are delayed

### ISSUE THREAD

**Issue by Webbah** [upb-lea/openmodelica-microgrid-gym#101]
Currently the state consist of obs(t) (->o) and agent.measurement(t-1) (->m) (action -> a): 
`o(0) -> a(0) -> m(0) -> o(1) -> a(1) -> m(1) -> s(2)...`

So to calculate the reward [m(0) -> o(1) -> a(1) ] is used, but [ o(1) -> m(1) ->a(1)] is needed. 

That leads in the reward function to the mistake that o(1) and m(0) are taken to calculate the reward.
So e.g. the setpoint (from m(t=0))  are delayed in comparison to the measurend currents (o(t=1)).
The control algorithm perfoms correctly but the history has to be changed to correct the plots and reward calculation.

Needed order: `o(0) -> m(0) -> a(0)  -> o(1) -> m(1) -> a(1) -> s(2)...`

So the observation (i_abc_meas) is processed into a measurement (i_dq0_meas) to calculate the needed action (m_abc).

- Move actions (*MVdq0) in https://github.com/upb-lea/openmodelica-microgrid-gym/blob/214a16d28a4a20618986934ea070685cfcc5e0db/openmodelica_microgrid_gym/aux_ctl/inverter_contollers.py#L393
to the environment.

Of course in all controllers:
https://github.com/upb-lea/openmodelica-microgrid-gym/blob/214a16d28a4a20618986934ea070685cfcc5e0db/openmodelica_microgrid_gym/aux_ctl/inverter_contollers.py#L335
https://github.com/upb-lea/openmodelica-microgrid-gym/blob/214a16d28a4a20618986934ea070685cfcc5e0db/openmodelica_microgrid_gym/aux_ctl/inverter_contollers.py#L242

- Split the whole control function into two part:
    - Measurement part: phase, abc->dq0
    - step part: apply controller.step()

**Comment by stheid** [comment]
pr merged
