### ISSUE TITLE
Add feedforward term to controller class

### ISSUE THREAD

**Issue by Webbah** [upb-lea/openmodelica-microgrid-gym#103]
Add a feedforward term to output in https://github.com/upb-lea/openmodelica-microgrid-gym/blob/ba63ebb6d14fdb2365186eb8c7a8c8183503b505/openmodelica_microgrid_gym/aux_ctl/pi_controllers.py#L44
and https://github.com/upb-lea/openmodelica-microgrid-gym/blob/ba63ebb6d14fdb2365186eb8c7a8c8183503b505/openmodelica_microgrid_gym/aux_ctl/pi_controllers.py#L45
so it is considered in the anti-windup:
`clipped = np.clip(output+FF, *self._params.limits)`
`self.windup_compensation = (output+FF - clipped) * self._params.kB`

- changes tests?

(rebase and delete PI_Controller_FF in #59 )

**Comment by stheid** [comment]
we should make sure, no-one confuses this with neural networks (feed forward). maybe by adding clarifying comments in the code

**Comment by Webbah** [comment]
done in #59 merged to dev
