### ISSUE TITLE
Introduction video of the toolbox

### ISSUE THREAD

**Issue by h-bode** [upb-lea/openmodelica-microgrid-gym#114]
I am currently busy with creating an introduction video for the first step into working with the toolbox.
The first part with introducing OpenModelica and the data transfer to python seems to be clear.

In Python, just showing the simple agent, saying that any kind of controlling algorithm can be added there, the net.yaml, and running the two_inverter_static_droop_control once with a loadstep?

Is there anything which should be shown? I hope that I can present a first version at the meeting on monday :)

**Comment by stheid** [comment]
dup with #121
