### ISSUE TITLE
droopParams in components.py

### ISSUE THREAD

**Issue by Webbah** [upb-lea/openmodelica-microgrid-gym#133]
In the Component class reference values are calculated to make them available to e.g. an RL-agent as input from the "environment".
To calculate the reference values the wanted frequency is needed to calculate the phase needed for ref_abc.

Currently we have defined the droop-parameters in the component class, too:

https://github.com/upb-lea/openmodelica-microgrid-gym/blob/1036dfd80d2f3ccb54c061d33f9332cbe99cd9bd/openmodelica_microgrid_gym/net/components.py#L125-L126

https://github.com/upb-lea/openmodelica-microgrid-gym/blob/1036dfd80d2f3ccb54c061d33f9332cbe99cd9bd/openmodelica_microgrid_gym/net/components.py#L97-L98

Problem:
- Twice droop params are defined
1. main script (static or as mutuable float to be optimized)
2. as default values in the component.py

If the droop values differ, that leads to different values in the (doubled?) reference values in the env history:
(master.SPVa: internal value from controller calulation;
inverter1.v_ref.0: from env.components logged ref value)

![grafik](https://user-images.githubusercontent.com/1822491/113881766-05643b00-97bd-11eb-8e32-0f5b860bc8d8.png)

- what happens if we optimize the droop controller value?
![1617804562033](https://user-images.githubusercontent.com/1822491/113882327-7dcafc00-97bd-11eb-9ab5-be46e94b2678.jpg)

the droop-params in the net will not be changed!
1. Do we need that?
2. is the "env"-ref value needed on the control-part on the agent side?
Or is it only needed in case of feeding an RL-agent?

Solution-suggestion:
Delete all droop-params in the components.py and make clear, that droop has to be considered externally.
@wallscheid Do we have a problem in that case if we want to "learn droop-control" with RL-agents?

**Comment by wallscheid** [comment]
If an agent is still able to alter the droop parameters acting on the control loops, I do not see any issue.

**Comment by Webbah** [comment]
Compromise: Left droop-params in the component class but set per default to zeros.
In that case it is possible to use them but per default they have no influence (like MasterInverter per definition calculates f(P) and does not reduce f if pDroopParams are zero).
