### ISSUE TITLE
Construction branch

### ISSUE THREAD

**Issue by h-bode** [upb-lea/openmodelica-microgrid-gym#41]
A construction branch with basically working parts and components, which are actually not used in the real applications, but might be used later on. 

At the beginning, mainly components for a correct frequency measurement which considers deviations from the nominal frequency are stored inside.

**Comment by stheid** [comment]
what is this issue about? Its not clear what is the task and when it can be seen as sovled

**Comment by wallscheid** [comment]
having archive-style branches is fine
