### ISSUE TITLE
Move reference to environment state

### ISSUE THREAD

**Issue by stheid** [upb-lea/openmodelica-microgrid-gym#43]
The environment should provide the agent with all information that is needed to learn problem. Currently the reward signal is calculated with respect to the error to the reference value. however the reference value is not provided by the environment. This makes it impossible for an task-agnostic agent to learn on this environment.

Additionally the references should also be provieded in the same type as the measurements. Eigther both in ABC or both in DQ0 and not mixed.

**Comment by wallscheid** [comment]
Yeah, I totally agree. A class "reference generator" would be nice, cf.
https://github.com/upb-lea/gym-electric-motor/tree/master/gym_electric_motor/reference_generators
