### ISSUE TITLE
Active loads using current sources

### ISSUE THREAD

**Issue by h-bode** [upb-lea/openmodelica-microgrid-gym#53]
Under specific circumstances, modeling active loads by current sources seem to work.

![active_load](https://user-images.githubusercontent.com/63717517/87759160-18d60d00-c80e-11ea-94f3-9596e916cc9f.png)

Main Problems: 
- Unstable if an eigenfrequency of the LC filter is hit
- Resistors which simulate losses in the LC filter for damping are required
- Error while simulating in OpenModelica occurs for unknown reason, but does not effect the simulation process or the result: _division by zero in partial equation: sqrt(network_singleInverter22.activ_z.pll_ueff.add1.y)
at Time=0.000000
solver will try to handle that._

First results after tuning of the LC-filter: p = 1kW, q = 2kVAr

![currents](https://user-images.githubusercontent.com/63717517/87760078-859dd700-c80f-11ea-9646-88bf3f4e963d.png)

**Comment by h-bode** [comment]
Same filter, but different load (p=2kW, q = 500VAr), totally different result!
![resonance](https://user-images.githubusercontent.com/63717517/87762485-833d7c00-c813-11ea-9626-731dc2f84030.png)

**Comment by h-bode** [comment]
Adding a butterworth lowpass at every phase current a,b,c, the previously bad results looks way better. The question is which influence a phase shift in this position has... 

![butterworth](https://user-images.githubusercontent.com/63717517/87771576-d9fd8280-c820-11ea-9dba-0db98f50c963.png)

**Comment by wallscheid** [comment]
Phase shift would mix up active and reactive power flow. That should be monitored and corrected e.g. by an additional controller :)

**Comment by h-bode** [comment]
Tuned Butterworth at the effective voltage in combination with a change of the "blackstart catcher" seem to solve the problem in OpenModelica. The resistor in the LC filter is still required, reducing it will increase the timespan oscillations occur in the signal

First try to control the inverters with the toolbox in python were not really successfull
