### ISSUE TITLE
JOSS Review Notes to Improve Stuff

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/openmodelica-microgrid-gym#55]
Feedback of katyhuff : 
- [x] Add readme information for highlight OS support (SH)
- [x] Classifiers in the setup.py accordingly (SH)
- [x] Send thanks feedback on JOSS issue (SH) 
- [x] Add DOIs to joss paper in markdown (HB)
- [x] Add in-line comments to high-level tests (more information to new users on the test background) (SH)
- [x] Add information to role of E. Hüllermeier (within review answer) plus add section 'individual contributions of the authors'. (HB) 
- [x] Add Jarren to thanks section (HB)
- [x] Clearification of the functionality scope (HB)
- [x] Add link to whitepaper and refer to detailed example usage information there (small paragraph on scope of examples) (HB)
- [x] Just go through comments of uploaded PDF and tune JOSS paper accordingly (HB)

**Comment by stheid** [comment]
@h-bode  please use branch https://github.com/upb-lea/openmodelica-microgrid-gym/tree/feature/joss-katyhuff

**Comment by h-bode** [comment]
Updated and pushed everything. 

@wallscheid , do you want to take an additional look?

@stheid since you made every communication in the past, are you going to present the new version to katy huff?

**Comment by stheid** [comment]
Where did you do the changes? the branch i mentioned above does not have a single commit from you

**Comment by stheid** [comment]
lgtm now #57 can be merged from my side
