### ISSUE TITLE
Measurement

### ISSUE THREAD

**Issue by Webbah** [upb-lea/openmodelica-microgrid-gym#59]
Test setup:
single inverter connected to RL (0.5 ohm, 2m2H).
Parameter tuning using safeopt

**Comment by Webbah** [comment]
toDo: double check reward function
J is not in the range it should be  

![grafik](https://user-images.githubusercontent.com/1822491/89042477-4a3ef480-d347-11ea-8e2d-c58eecb377c7.png)

**Comment by wallscheid** [comment]
Ideas:
* Check/plot against reference values
* Check reward function calculation (bug?)
* Current sensor offset check
* Check if (parts) of the harmonics come from sampling during or shortly after switching instants of the IGBTs

**Comment by JarrenLange** [comment]
Feedback from the hardware has been extended to include the direction reference values. 

Working on obtaining required hardware for current sensor verification.

For Sampling modification, changes to the hardware to choose when to sample and/or to change the internal carrier (forward,reverse, symmetric) are underway.

**Comment by JarrenLange** [comment]
Using the setpoints from the FPGA hardware seems to solve most of the problems. Turns out calculated SPs (derived from the I_D setpoint and the phase angle) differed significantly.

**Comment by Webbah** [comment]
Second try 1D for ki (kp = 0.01 1/A) current controller layout.

Resulting GP for ki_init = 20 1/(As), lengthscale = 5 /(As):

![grafik](https://user-images.githubusercontent.com/1822491/89291973-c85b0e00-d65b-11ea-9631-448409279d05.png)

Initial currents: 
![grafik](https://user-images.githubusercontent.com/1822491/89292000-dd37a180-d65b-11ea-85be-772d420d7ec2.png)

"Best" Result for ki = 11.7 /(As):
![grafik](https://user-images.githubusercontent.com/1822491/89292071-fe988d80-d65b-11ea-919e-a4eccf50654a.png)

toDo:
* Inital ramp up not the best, tune kp ->2D problem!
* Safe theshold here choosen = 0 due to higher exploration and testing. But 0 would mean infinit error! Choose above 0 from now on

**Comment by wallscheid** [comment]
great intermediate result! nice progress

quick question on the current waveforms: it seems that the three phase current is not idea, even in steady state (e.g. blue current is always too large for negative peak and green current is always too low for positive peak values). did you run an offset and gain compensation for all three current sensors before runing the experiment? Or do you have other ideas where the asymmetry / harmonics is coming from?

**Comment by JarrenLange** [comment]
It seems to stem from an unbalanced filter inductance, especially in a short circuit and with low V_dc values. 

DQ0 control struggles with this. We do see the imbalanced currents in the verification probes. So I do not think it is an error with the measurement circuit.

**Comment by Webbah** [comment]
Intermediate result in 2D (x->kp, y->ki; interrupted by ss connection error)

![grafik](https://user-images.githubusercontent.com/1822491/89303722-da917800-d66c-11ea-9650-376916e35db0.png)

initial:
![grafik](https://user-images.githubusercontent.com/1822491/89303774-eb41ee00-d66c-11ea-9b60-afc6045b517c.png)

currently best one (green dot, first pic)
![grafik](https://user-images.githubusercontent.com/1822491/89303958-2a703f00-d66d-11ea-8371-36b3c6c89116.png)

**Comment by wallscheid** [comment]
Very nice result for 2D optimization. Here also the asymmetry is mostly gone -> interesting.

**Comment by Webbah** [comment]
Second try, higher lentghscale (reaches unsafe point (kP=0 in plot below), but with less results more exploration...)

![grafik](https://user-images.githubusercontent.com/1822491/89305483-fbf36380-d66e-11ea-9e76-9e2994201cb5.png)

Yes, also first thought maybe tuning... but unbalanced L the case, too....

**Comment by Webbah** [comment]
![grafik](https://user-images.githubusercontent.com/1822491/89529904-d8a2f280-d7ed-11ea-9ed8-8493166f9f2a.png)
Comparison for same tuning of the current controller, showing only current through phase a at the moment

**Comment by Webbah** [comment]
![grafik](https://user-images.githubusercontent.com/1822491/89622117-cfb82c80-d892-11ea-9687-704ed1555223.png)
 
error(kP,kI) landscape from testbench

**Comment by Webbah** [comment]
Plan:
Controller layout in simulation (Pt1 -> RL & Pt1 -> Inverter), 
Magnitude Optimum -> Kp&Ki_init
Estimate maximum lengthscale -> Use for measurement

- Voltage Controller -> same

- Apply loadsteps; wait for steady state -> full load -> half load

**Comment by wallscheid** [comment]
Idea to make the simulation model becomer closer to reality:
add white noise to the current (and voltage) 'measurements' within the Python interface to the OM-FMU container.
mean = zero
Variance = take a snapshot time period from the test bench with actively swichting transistors controling a zero current / zero voltage. the measured signals can be then assumed to be the pure noise component and used to estimate the variance of the noise process.

**Comment by JarrenLange** [comment]
Issue with sensor overcurrent is likely an underperforming op-amp.

Sensor uses a transimpedance amplifier to convert the current output (25mA nominal) from LEM LAH 25-NP (which has a 1:1000 conversion ratio). The op-amp (TL082) only has a 20mA maximum source/sink. 

Options:
 
1. Buy pin compatible op-amp with ~60mA source sink limit.
2. Modify circuit to let the LEM device terminate over the resistor and use the op-amp for general gain/filtering.
3. Use transistors in a push-pull combination on the output of the op-amp.

Investigating option 1 at the moment.

**Comment by Webbah** [comment]
Noise measurement for current measurements from testbench: max(standard deviation) of 0.11 A detected

- [ ] Add measurement noise to env-step

At the moment len(obs)*std(noide_measurement) is taken. 
For voltage control that has to be adjusted

- [ ]  Assign different noise do different CVs

**Comment by JarrenLange** [comment]
Adjusted the current sensors using option 2 as mentioned above. Different gains for system (3.6A/V to 6A/V).

But we can now have currents over 30A without non-linear behaviour 
![grafik](https://user-images.githubusercontent.com/7976199/90396963-6bb61500-e097-11ea-9504-d6da902f988d.png)

**Comment by Webbah** [comment]
**Current controller layout using safeopt - Testbench**
- Controller layout using magnitude optimum (measurement noise included)
- figured out maximum possible ('safe') lengthscale using simulation setting

![lensearch](https://user-images.githubusercontent.com/1822491/90748550-9c35c300-e2d2-11ea-91f8-3006b01fed2b.jpeg)
(y-axis: lengthscale for kp, x-axis: lengthscale for ki; green -> safe; blue circle -> chosen point for measurement)

Result:
![agent_plt](https://user-images.githubusercontent.com/1822491/90764383-8b904780-e2e8-11ea-9d85-1c7cd811282d.png)

Initial controller tune:
[J_1.0_abcInductor_currents.pdf](https://github.com/upb-lea/openmodelica-microgrid-gym/files/5102607/J_1.0_abcInductor_currents.pdf)

[J_1.0_dq0Inductor_currents.pdf](https://github.com/upb-lea/openmodelica-microgrid-gym/files/5102609/J_1.0_dq0Inductor_currents.pdf)

**Best result**
Performance increase by 11.58 %
But more noise on it, run for longer?
Weight the initial error less or the "later" error  ('noise' around the setpoint) higher?
So slower step response but less noise?  
[J_1.1158069816015708_abcInductor_currents.pdf](https://github.com/upb-lea/openmodelica-microgrid-gym/files/5102619/J_1.1158069816015708_abcInductor_currents.pdf)

[J_1.1158069816015708_dq0Inductor_currents.pdf](https://github.com/upb-lea/openmodelica-microgrid-gym/files/5102620/J_1.1158069816015708_dq0Inductor_currents.pdf)

**Comment by Webbah** [comment]
First try with voltage controller running on open circuit using analytical current controller layout results.

![agent_plt](https://user-images.githubusercontent.com/1822491/90783076-ec774a00-e2ff-11ea-8cd1-eb6f7b407c2d.png)
 
Initial result (without analytical layout): 
(Performance in the title)

![grafik](https://user-images.githubusercontent.com/1822491/90783266-26e0e700-e300-11ea-8fd0-8cfbf255b144.png)


Best result after 100 epsiodes:
![grafik](https://user-images.githubusercontent.com/1822491/90783357-41b35b80-e300-11ea-8d82-be75eeb1b620.png)

**Comment by wallscheid** [comment]
Are the following stuff results from the test bench or simulation? Was not 100 % sure from your text input.

> ![grafik](https://user-images.githubusercontent.com/1822491/90765533-67ce0100-e2ea-11ea-8ae2-9a06c62f7cc2.png)
> 
> ![grafik](https://user-images.githubusercontent.com/1822491/90765489-4ec55000-e2ea-11ea-8d2e-51215e1e8887.png)
> 
> **Best result**
> Kpi = [0.9626728565572376, 24.507337238803796] (green circle in the agent plot above)
> Performance increase by 11.58 %
> But more noise on it, run for longer?
> Weight the initial error less or the "later" error ('noise' around the setpoint) higher?
> So slower step response but less noise?
> 
> ![grafik](https://user-images.githubusercontent.com/1822491/90765652-9b109000-e2ea-11ea-937a-da919fb3a3e2.png)
> 
> ![grafik](https://user-images.githubusercontent.com/1822491/90765807-e0cd5880-e2ea-11ea-9cd0-7b9e48f74967.png)

Regarding the noise in steady-state: Did you use the mean root error (MRE) as the cost criterion (as in the preprint paper) or something different? Normaly the MRE is quite a suitable cost function to ensure nice behavior in steady-state since smaller control errors are not squeezed-together compared to the standard MSE.
Nevertheless, with respect to the results the noise amount is increased, yes, but with the initial controller parameters there was also some significant harmonics on the current which are suppressed with the optimal tuning design.

**Comment by wallscheid** [comment]
Additional question regarding the current controller results: How close are not the behavior from the simulation and the experimental optimization? Is the performance landscape and the optimal found controller gains both similar in simulation and experiment?

**Comment by Webbah** [comment]
**This is simulation**
![grafik](https://media.giphy.com/media/mxQUQbIjXMSwo/giphy.gif)

![grafik](https://user-images.githubusercontent.com/1822491/90865328-8687d280-e392-11ea-87f7-27899242f628.png)

Initial episode: J = 1
![grafik](https://user-images.githubusercontent.com/1822491/90865543-cd75c800-e392-11ea-855e-b8f7214cbab7.png)
![grafik](https://user-images.githubusercontent.com/1822491/90865615-e5e5e280-e392-11ea-9557-5f2af3552cbb.png)


Best episode: J = 1.25
![grafik](https://user-images.githubusercontent.com/1822491/90865387-96071b80-e392-11ea-9996-13a08300da01.png)
![grafik](https://user-images.githubusercontent.com/1822491/90865750-29d8e780-e393-11ea-8615-dcfcc48bf80a.png)

**Comment by JarrenLange** [comment]
Issue with sensor overcurrent is likely an underperforming op-amp.

Sensor uses a transimpedance amplifier to convert the current output (25mA nominal) from LEM LAH 25-NP (which has a 1:1000 conversion ratio). The op-amp (TL082) only has a 20mA maximum source/sink. 

Options:
 
1. Buy pin compatible op-amp with ~60mA source sink limit.
2. Modify circuit to let the LEM device terminate over the resistor and use the op-amp for general gain/filtering.
3. Use transistors in a push-pull combination on the output of the op-amp.

Investigating option 1 at the moment.

**Comment by JarrenLange** [comment]
I have checked the DC-Link behaviour of the system during the open-circuit and short circuit tests.
Here are the waveforms
Under short circuit (first 100ms of DC bus noise is with no modulation, performing a current nulling test).
![LeCroy--00004](https://user-images.githubusercontent.com/7976199/91027666-af130500-e5fc-11ea-9a52-2b13aef9edb1.jpg)

Under open circuit
![LeCroy--00002](https://user-images.githubusercontent.com/7976199/91027779-cbaf3d00-e5fc-11ea-8f42-e6952132075b.jpg)

**Comment by wallscheid** [comment]
I do not get the voltage measurement. I would expect to see the average DC-link voltage (at around 60 V?) and then some ripple and a possible dip (when starting the current control) on top. Assuming that above the orange signal is the DC-bus, why it is around 0 V?

**Comment by JarrenLange** [comment]
Orange is the VDC bus (AC Coupled), the bottom display is the currents or voltages.

Note, this measurement was taken using the custom voltage sensors. I will test it soon with an independant differential probe.

**Comment by JarrenLange** [comment]
![LeCroy--00005](https://user-images.githubusercontent.com/7976199/91038635-631b8c80-e60b-11ea-99ee-998a093fab4c.jpg)

Repeated short circuit test, but with 2 sensors for the VDC (Given here in absolute units).

**Comment by Webbah** [comment]
results in paper, branch mereg to develop
