### ISSUE TITLE
[install] Modify readme to properly explain installation with conda

### ISSUE THREAD

**Issue by stheid** [upb-lea/openmodelica-microgrid-gym#6]
create&activate conda env
condaforge install pyfmi
pip install openmodelica-microgrid-gym

**Comment by stheid** [comment]
please refer to miniconda https://conda.io/en/latest/miniconda.html

**Comment by h-bode** [comment]
Will the quick-fix be done right now, or do shall I add a sentence to gpy and sofeopt?

**Comment by stheid** [comment]
#8
