### ISSUE TITLE
Examples contain static/local paths, resulting with errors at the user

### ISSUE THREAD

**Issue by stheid** [upb-lea/openmodelica-microgrid-gym#60]
https://github.com/upb-lea/openmodelica-microgrid-gym/blob/develop/examples/single_inverter_voltage_current_control_safe_opt.py#L190

Either remove the specific lines or add code to create the directory (https://docs.python.org/3/library/os.html#os.makedirs)

**Comment by stheid** [comment]
https://github.com/upb-lea/openmodelica-microgrid-gym/blob/develop/examples/two_inverter_droop_safe_opt.py#L198

Similarly here

**Comment by Webbah** [comment]
Isn't that one already solved or why still open?
Did PR at 07.08.

**Comment by stheid** [comment]
i think so.
