### ISSUE TITLE
Monte-Carlo-based simulation

### ISSUE THREAD

**Issue by Webbah** [upb-lea/openmodelica-microgrid-gym#68]
To represent real world more accurately, define parameters as distribution (gaussian, normal).
- In every simulation step, drag from distribution and simulate, calculate performance.
- Do this e.g. 10 times with the same controller parameter set
- Use mean value of the performance in the optimizer associated with the controller parameter set

Parameters: 
- R, L, C
- vDC?
- Noise
- Alter all phases at once
- Alter L1 L2 and L3 separately

(Implementation will be done in #59 )

**Comment by Webbah** [comment]
_n_MC_: number of Monte-Carlo samples as input to runner

**runner**
- [ ] Additional n_MC-loop  

**Env**:
Every n_MC simulation: new parameters are drawn
-> update env parameters in env.reset()

- [ ] get parameter value from distribution (using partial?)
Where to set new R/L values?


**Agent:** only has to update after n_MC simulations
Every n_MC simulation: new performance is calculated
After n_MC -> average performance used for optimization to find next controller parameters  

- [ ]  counter to optimize only after n_MC
- [ ] vector to store all n_MC performance measuremnts

**Comment by Webbah** [comment]
Changed env.reset() to initialize model parameters with different values using `model_param` :
https://github.com/upb-lea/openmodelica-microgrid-gym/blob/c845d1a7769c67ba203bbfeeaa510a09e4cde95d/openmodelica_microgrid_gym/env/modelica.py#L263

Even solves the problem that the first parameter value (before the first step) is correct and avoids loadsteps in the beginning.

@stheid  better possibility or other suggestion? Or where else are the initial parameters (from python) set yet?

**Comment by stheid** [comment]
I mean, OpenModelicaParameters can be functions of any type, so this is not an issue from an implementation state. But you also mean to addidionally parametrize the rest of the environment, right?

**Comment by Webbah** [comment]
Problem with additional Load class in main script:
 - R,L parameter get initialized randomly -> Only during initialization!
 - initialization has to take place every MC-step, not once in the beginning

@stheid ideas for structure?

**Comment by Webbah** [comment]
- [ ] add delay (1 timestep) between controller and env
- [ ] use unbalanced loads

**Comment by Webbah** [comment]
Implemented in #59
