### ISSUE TITLE
Fix basic examples in Documentation

### ISSUE THREAD

**Issue by stheid** [upb-lea/openmodelica-microgrid-gym#72]
The reviewer found out that our basic examples are somehow broken. I assume the folder structure of the documentation changed and therefore the includes are broken (even though i have no idea how this has happened.

**Comment by wallscheid** [comment]
@h-bode : Can you please support fixing the example / documentation problems?

**Comment by h-bode** [comment]
solved, the paths were slightly changed, builds again :-)
