### ISSUE TITLE
Add progress bar for long-running simulations

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/openmodelica-microgrid-gym#9]
If single simulations really need a lot of time (e.g. static droop example with +100 ms simulation time horizont) it would be comfortable to have a progress bar on the simulation progress per episode. In some cases, new users might be irritated if their computer starts running up the CPU fan and nothing is really happening in the command line.

For advanced user which would like to simulate multiple episodes as fast as possible, the progress bar should be easily deactivated.

**Comment by stheid** [comment]
I decided not to give an option to disable the progress bar. tqdm is extremely efficient and i also changed the way the inner progress bar is displayed so that i see no advantage of disabling the progressbar
