### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by h-bode** [upb-lea/openmodelica-microgrid-gym#95]
I just installed the omg toolbox in the recommended way on my new windows laptop.

Two problems occured:

- GPy could not be installed via pip

Manual installation with pip install GPy throws following error.
Following error: 
![gpy error](https://user-images.githubusercontent.com/63717517/96140849-ac4bd680-0f00-11eb-93d3-6f5027cae990.png)

It could be solved by installing it via condaforge, similar to PyFMI:

` conda install -c conda-forge gpy `

- safeopt is not installed automatically by using `pip install openmodelica_microgrid_gym`

Trying to click on the pop-up on top of pycharm with missing requierements didnt install it, although it was listed as a missing on.

Running `pip install safeopt` manually solved this problem.

**Comment by stheid** [comment]
https://github.com/upb-lea/openmodelica-microgrid-gym/blob/1404234874808b02ee25123d9e3db4ab512715c6/requirements.txt#L13-L14

hm, don't understand it. Can you check again in a clean environment? makes no sense to my why GPy should not install...
