### ISSUE TITLE
Feature request in net_single-inv-curr.yaml

### ISSUE THREAD

**Issue by marvpick** [upb-lea/openmodelica-microgrid-gym#99]
![Github_Issue](https://user-images.githubusercontent.com/65189804/96699106-31fed480-138e-11eb-99e3-d03587994fe7.PNG)

As you can see in the attached screenshot, you cannot access the resistance values in net_single-inv-curr.yaml. The red-marked command does not work, the error message follows: **"AttributeError: <class 'openmodelica_microgrid_gym.net.components.Load'> no such attribute: R, please validate ../net/net_single-inv-curr.yaml."** You can only access the resistance values if you note them in the list of electrical currents.

**Comment by stheid** [comment]
That's less a bug than a feature request.

Currently you can only set values in the yaml that have a corresponding field ind the class implementations constructor (in this case `net.components.Load`)

## ideas on implementation
perhaps the `net.components.Component` class could get be able of reading any kwargs which handle those parameters.
